# Generated by Django 3.1.2 on 2020-10-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201021_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
